modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
    modId="lousiesutilities"
    version="${file.jarVersion}"
    displayName="LousiesUtilities"
    credits="Thanks to the OpenMods team for heavily inspiring this project"
    authors="OneLousyGamer"
    description='''A mod that contains a bunch of useful utility blocks and items. Heavily inspired from OpenBlocks.'''
[[dependencies.lousiesutilities]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lousiesutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"